Planet-NULLCAST/curriculum

- README.md
There needs a contributing guideline for commit messages and workflow for adding a feature
This will fix https://github.com/Planet-NULLCAST/curriculum/issues/5
> feat(readme): Add a contributing guideline

- website/component/editor/Editor.js
- website/component/layout/NavBar/NavBar.jsx
- website/next.config.js
- website/package-lock.json
- website/package.json
- website/pages/Javascript/[id].js
- website/pages/index.js
A new codemirror editor is added to our learning dashboard.
> Feat: added editor to dashboard

- courses/javascript/variables.md
Update doc for variable
Include var, const and let
> doc: Variables

- component/layout/SideBar/SideBar.jsx
Runtime Error  was resolved with 'if-exists' operator at lines 13 and 46
fixes issues #43 and #44
> Fix: Unhandled Runtime Error in SideBar resolved

- component/layout/ChapterList/ChapterList.jsx
- component/layout/ChapterOverview/ChapterOverview.jsx
- component/layout/CourseItem/CourseItem.jsx
- component/layout/CourseJourney/CourseJourney.jsx
- component/layout/CourseList/CourseList.jsx
- component/layout/CourseSpotlight/CourseSpotlight.jsx
- component/layout/CourseSpotlight/CourseSpotlight.module.scss
- component/layout/SectionSwag/SectionSwag.jsx
- component/layout/SiteFooter/SiteFooter.jsx
- component/layout/SiteHeader/SiteHeader.jsx
- pages/curriculum/[courseName]/index.js
- pages/curriculum/index.js
- pages/index.js
- styles/globals.scss
> Initial integration of courses page and chapters page

- component/myblogs/WriteNav.jsx
- next.config.js
- pages/posts/write.js
integrate ghost editor as an iframe
send and recieve post messages from the iframe
> feat: ghost-editor integration

- package-lock.json
- tailwind.config.js
- yarn.lock
Integrate ghost editor
send and recieve post message between iframe and parent
> Feat: ghost editor

- component/myblogs/WriteNav.jsx
- pages/posts/write.js
- move form submit to writeNav
- add slug
- Fix: image upload - get url from s3
> Feat: Fetch data from post for post settings, add function to delete post

- component/layout/SiteHeader/SiteHeader.jsx
- pages/login.js
> Fix: Logout from protected routes should redirect to home

- component/myblogs/WriteNav.jsx
- component/popup/ModalConfirm.jsx
- package-lock.json
- package.json
- styles/globals.scss
> confirmation popup

- component/layout/BlogListing/AuthorDetails.jsx
- component/layout/BlogListing/Listing.jsx
- component/layout/BlogListing/ListingItem.jsx
- component/myblogs/Navbar.jsx
- component/myblogs/WriteNav.jsx
- pages/tag/[tagName].js
- services/PostService.js
- utils/tags.js
- Create tag/[tagName]
- Tag api integration
- Add load more function
> Feat: Create a page for tags

- component/editor/RunButton.jsx
- component/layout/Profile/Profile.js
- component/layout/SiteHeader/SiteHeader.jsx
- component/myblogs/WriteNav.jsx
- pages/curriculum/[courseName]/[chapterName].js
- pages/login.js
- pages/posts/write.js
- pages/signup.js
> Fix: Login and Signup page shouldn't be accessible if user is already logged in, multiple cookie issue

- component/layout/BlogListing/Listing.jsx
- component/layout/ListingHeader/ListingHeader.jsx
- component/layout/ListingHeader/ListingHeader.module.scss
- config/config.js
- pages/search.js
- services/PostService.js
> Feat: Create search page for blogs

- component/layout/BlogPost/SectionRelated.jsx
- pages/404.js
- pages/[blogPost].js
- pages/blog.js
- pages/p/[postId].js
- pages/posts/write.js
- pages/search.js
- pages/signup.js
> Feat: Add latest posts section to 404

- component/ButtonLoader/LoadIcon.jsx
- component/layout/BlogListing/AuthorDetails.jsx
- component/layout/BlogPost/SectionAuthor.jsx
- component/layout/Profile/Profile.js
- component/layout/SectionBlogs/SectionBlogs.jsx
- component/layout/SectionUsers/SectionUsers.jsx
- component/layout/SiteHeader/SiteHeader.jsx
- component/myblogs/WriteNav.jsx
- pages/posts/index.js
- pages/posts/write.js
- pages/u/[username].js
- services/PostService.js
> Add profile links, Use serversideprops for redirecting at posts

- pages/settings.js
- styles/Settings.module.scss
> Style: edit profile page style

- component/layout/Profile/Profile.js
- component/layout/SiteHeader/SiteHeader.jsx
- component/profile/Count.jsx
- component/profile/FollowersList.jsx
- component/profile/Navbar.jsx
- component/profile/ProfileDetails.jsx
- component/profile/Trails.jsx
- pages/reset-password.js
- pages/settings.js
- pages/u/[username].js
- services/PostService.js
- Hide unused elements in profile
- Add profile image
> Profile changes

- component/admin/AdminBlogsList.jsx
- component/editor/RunButton.jsx
- component/layout/BlogPost/BlogPost.jsx
- component/layout/BlogPost/BlogPost.module.scss
- component/layout/BlogPost/SectionAuthor.jsx
- component/layout/Profile/Profile.js
- component/layout/SectionBlogs/SectionBlogs.jsx
- component/layout/SiteFooter/SiteFooter.jsx
- component/myblogs/WriteNav.jsx
- pages/[blogPost].js
- pages/_app.js
- pages/admin.js
- pages/change-password.js
- pages/curriculum/[courseName]/[chapterName].js
- pages/forgot-password.js
- pages/index.js
- pages/login.js
- pages/p/[postId].js
- pages/posts/write.js
- pages/settings.js
- pages/signup.js
- styles/globals.scss
> Misc fixes

- component/layout/SiteFooter/SiteFooter.jsx
- component/profile/BlogList.jsx
- component/profile/SkillSet.jsx
- pages/forgot-password.js
- pages/u/[username].js
- services/PostService.js
> Feat: add view all option for blogs in user page

- component/admin/AdminBlogsList.jsx
- component/editor/RunButton.jsx
- component/layout/CourseJourney/CourseJourney.jsx
- component/layout/CourseList/CourseList.jsx
- component/layout/SiteHeader/SiteHeader.jsx
- component/myblogs/MyBlogs.jsx
- component/pagination/pagination.jsx
- component/profile/ProfileDetails.jsx
- pages/login.js
- pages/posts/index.js
- pages/u/[username].js
- services/PostService.js
- Feat: Add unpublish functionality for admin page
- Fix: seo duplicate url issue
- Fix: Add content in course list page
- open edit link and title link in new tab
> Unpublish in admin, seo url issue etc

- .commitlintrc.json
- .husky/commit-msg
- .npmrc
- package.json
- yarn.lock
add commit lint
add standard version
add husky githooks
allow only yarn as a package manager
> chore: enforce neoito guidelines

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
add pr template
add bug report template
add feature template
> chore: enforce  neoito guidelines

- component/layout/BlogPost/BlogSpotlight.module.scss
- pages/_app.js
adjusted width in blogspotlight added new meta content
adjusted width in blogspotlight added new meta content
> fix image size in blogs #258 #256

- pages/p/[postId].js
enable public preview of blogs
enable public preview of blogs
Fixes #260
> fix: public preview of blogs

- component/myblogs/WriteNav.jsx
- component/popup/ImageCropper.jsx
- pages/settings.js
- yarn.lock
image crop added in the upload post image
Fixes #263 
> #263 feat: image-crop

- README.md
- package-lock.json
Reverts Planet-NULLCAST/curriculum#325
> Revert "fix: replace npm with yarn and delete npm package.lock file"

- pages/login.js
- pages/signup.js
Removed auto focus on email on login page and full name on signup page which was causing the issue.
Fixes #313 
Tested locally and followed the steps shown in the video.
> fix: login and signup issue

- pages/forgot-password.js
Enhanced forgot password page as per the common UI
Fixes #279
> feat: Forgot Password Page Enhancement #279 

- README.md
- env.example
updated env.example file with relevant variables ,
mentioned in the readme about developement branch has the latest code
fixes  #327
tested locally and verified in github readme preview
> docs: updated sample evn ,readme files

- courses/javascript/hello-world.md
- courses/javascript/introduction.md
* Updated content and spacing for `courses/javascript/introduction.md`
* Updated content for `courses/javascript/hello-world.md`
* Added inline code blocks
* Fixes spacing issues
* Updated mostly grammar and capitalizations (html to HTML, javascript to JavaScript)
Introduction changes with spacing:
Fixes #316 
Run the server locally and visit the following pages to verify the updated content:
http://localhost:3000/curriculum/javascript
http://localhost:3000/curriculum/javascript/hello-world
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have added tests that prove my fix is effective or that my feature works
> docs: update content of chapters 1 and 2

- component/layout/SideBar/SideBar.jsx
- pages/curriculum/[courseName]/[chapterName].js
fixed scroll top issue in chaptername 
Fixes #284 
using localhost
- [x I have performed a self-review of my own code
> 284 fix/scroll fix chapter

- courses/javascript/arrow-functions.md
- courses/javascript/asynchronous-behaviour-and-event-loop.md
- courses/javascript/foreach-map-filter.md
- courses/meta.js
✍🏼 Added curriculum content : Foreach vs map vs filter
Fixes #273 
Tested by completing the task cases myself.
> content : Added Foreach vs Map vs Filter Curriculum content #273

- courses/javascript/function.md
javascript content changed in chapter 10 and 11
Fixes #319 
local host
> fix: content change in chapter in javascript #319

- courses/javascript/arithmetic-operators.md
- courses/javascript/if-condition.md
- courses/javascript/switch-statement.md
Javascript content changed in chapter 6, 7 and 8
Fixes #318 
local host
> fix: content change in Javascript #318

- pages/login.js
- pages/signup.js
- services/AuthService.js
Invalid cookie persisting in browser preventing user from logging in.
Cookie was not being cleared upon receiving 401. Also page reloads in login page due to this error. Login automatically on signup feature brought back in
Fixes #350
By clearing userNullcast cookie, invalidating http cookie and accessing server. Login page refreshing issue was tested by inputting invalid creds.Automatic signin upon signup feature tested by signing up into a new account
> fix: unable to login due to invalid cookie

- component/myblogs/MyBlogs.jsx
- component/myblogs/WriteNav.jsx
- config/config.js
- pages/posts/index.js
- pages/posts/write.js
- services/PostService.js
- services/TagService.js
fixed write page save to draft , publish and fixes
Fixes #348 
postman and localhost
> fix: write page api and fixes #348

- pages/signup.js
added success toast when user successfully sign's up
Fixes #340 
> feat: added success toast after user sign's up successfully

- courses/javascript/foreach-map-filter.md
fixed inline block and content 
Fixes #365 
> fix: fixed inline block and content for issue#365

- component/profile/ProfileDetails.jsx
- pages/u/[username].js
- services/UserService.js
profile page 404 fixed
Fixes #339 
loaclhost
> fix: profile page fixed #339

- component/myblogs/WriteNav.jsx
- config/config.js
- pages/posts/write.js
- services/PostService.js
- services/TagService.js
completed post save to draft,review,save,delete post and fixes
Fixes #348 
locally
> fix: api and fixes #348

- component/admin/AdminNavbar.jsx
- component/layout/BlogPost/BlogPost.jsx
- component/layout/BlogPost/SectionAuthor.jsx
- component/myblogs/WriteNav.jsx
- config/config.js
- pages/p/[postId].js
- pages/posts/write.js
- services/PostService.js
- services/TagService.js
fixed rendering issues in write page tag deletion added
Fixes #348 
> 348 write page api functionality

- component/layout/EventDetails/BookEvent.jsx
- component/layout/EventDetails/BookEvent.module.scss
- component/layout/EventDetails/Detail.jsx
- component/layout/EventDetails/Detail.module.scss
- component/layout/EventDetails/EventSpotlight.jsx
- component/layout/EventDetails/EventSpotlight.module.scss
- component/layout/EventDetails/GuestDetails.jsx
- component/layout/EventDetails/GuestDetails.module.scss
- component/layout/EventLayouts/EventDate.module.scss
- component/layout/EventLayouts/EventFeatured.jsx
- component/layout/EventLayouts/EventFeatured.module.scss
- config/config.js
- pages/events/[event_id].js
- public/images/event_bg.svg
- services/EventService.js
Added UI of Event details page
Fixes #324
> Style: added Event Details Page UI #324

- component/admin/AdminNavbar.jsx
- component/layout/BlogPost/BlogPost.jsx
- component/layout/BlogPost/SectionAuthor.jsx
- component/layout/SiteHeader/SiteHeader.jsx
- component/myblogs/Navbar.jsx
- component/myblogs/WriteNav.jsx
- component/pagination/pagination.jsx
- config/config.js
- pages/p/[postId].js
- pages/posts/index.js
- pages/posts/write.js
- services/PostService.js
- services/TagService.js
fixed pagination problem in write post page
Fixes #376 
> 376 fix/pagination write page

- component/layout/Profile/Profile.js
- component/profile/BlogList.jsx
- component/profile/ProfileDetails.jsx
fixed view all issue in profile blog list
Fixes #414 
t details for your test configuration
> fix: view all in profile blog #414

- component/layout/BlogListing/ListingFeatured.jsx
- component/layout/SectionUsers/SectionUsers.jsx
- pages/blog.js
- pages/index.js
- services/PostService.js
- services/UserService.js
Home page latest users added, published post listing added , blog page published post not listing issue fixed
Fixes #424
> 424 fix/home latest user posts

- courses/javascript/asynchronous-behaviour-and-event-loop.md
- package-lock.json
- package.json
fixed content changes and inline code block of js course chapter 13
Fixes #364 
> 364 content changes and inline code block of js course chapter 13

- pages/settings.js
- pages/u/[username].js
fixed settings view , username latest post added in profile page
Fixes #412
> fix: profile setting  #412

- public/images/svgs/pointer.svg
- styles/globals.scss
> feat: added custom mouse pointer

- component/layout/BlogPost/BlogSpotlight.jsx
- component/layout/BlogPost/SectionAuthor.jsx
- component/layout/BlogPost/SectionRelated.jsx
- pages/[blogPost].js
- services/PostService.js
getpostbytags getpost using slug api fixed also fixed some rendering issues
Fixes #431
> fix: post slug api fixed #431

- component/myblogs/WriteNav.jsx
- config/config.js
- services/TagService.js
fixed tag issues in write post settings page working fine create select and delete tag from a post
Fixes #449
> fix: tags delete update create write #449

- pages/posts/index.js
- services/PostService.js
Change api in write post rendering issue fixed
Fixes #430 
postman, localhost
> fix: api changed #430

- pages/index.js
- pages/settings.js
- services/UserService.js
update user profile api connected 
Fixes #433 
postman
> 433 fix/settings update profile

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- config/config.js
- pages/admin/create-event.js
- services/EventService.js
- tailwind.config.js
- yarn.lock
> Create event page

- component/layout/SectionUsers/SectionUsers.jsx
fixed user without userName in diagonal scroll in Home Page 
Fixes #440 
> fix: fixed issue440 fixed the user without userName in diagonal scroll in Home page

- pages/settings.js
- pages/signup.js
connected update user profile api and signup toast error fixed
Fixes #433 
> fix: settings page api #433

- courses/meta.js
- courses/ui-mastery/bootstrap-basics.md
- courses/ui-mastery/css.md
- courses/ui-mastery/html-accessibility.md
- courses/ui-mastery/html.md
- courses/ui-mastery/introduction.md
- courses/ui-mastery/js-basics.md
- courses/ui-mastery/learn-css-flexbox-and-media-queries.md
- courses/ui-mastery/naming-standard-bem.md
- courses/ui-mastery/optimization.md
- courses/ui-mastery/progressive-web-apps.md
- courses/ui-mastery/sass.md
- courses/ui-mastery/scss.md
- courses/ui-mastery/ui-debug-tools.md
- courses/ui-mastery/ui-standards.md
- courses/ui-mastery/workshop-practise-1.md
- courses/ui-mastery/workshop-practise-2.md
- courses/ui-mastery/workshop-practise-3.md
- courses/ui-mastery/workshop-practise-4.md
- courses/ui-mastery/workshop-practise-5.md
- courses/ui-mastery/workshop-practise-6.md
- courses/ui-mastery/workshop-practise-7.md
- courses/ui-mastery/workshop-practise-8.md
Added UI mastery content to curriculum courses
Fixes #478 
> Add UI mastery section

- component/myblogs/WriteNav.jsx
- config/config.js
- pages/index.js
- pages/settings.js
- services/SkillService.js
added userskill in profile page
Fixes #433
> fix: api fixes #433

- component/layout/BlogListing/Listing.jsx
- component/layout/BlogListing/ListingItem.jsx
- component/profile/SkillSet.jsx
- pages/tag/[tagName].js
> fix: event create api #471

- component/myblogs/WriteNav.jsx
- pages/signup.js
- pages/whats-new.js
when a User clicks on the button "Publish" in the Post Edit page, a Confirmation popup will display
Fixes #447 
local host
> 447 post edit page

- pages/login.js
login success message added on login screen when login success
Fixes #493
> fix: login toast fixed: #493

- component/layout/CourseList/CourseList.jsx
- pages/curriculum/[courseName]/[chapterName].js
adding UI mastery in courselist & changed label accordind to course
Fixes #481 
> 481 adding UI mastery in courselist

- services/PostService.js
The image upload api was throwing cors error.
Created a new axios instance with credentials false and use it to get the presigned url
Fixes #377 
> fix: image upload cors

- courses/javascript/datatypes.md
- courses/javascript/function.md
- courses/javascript/logical-operators.md
- courses/javascript/variables.md
Javascript content changed in chapter 3, 4 and 5
Fixes #317 
Local host
> fix: Content changed in javascript #317

- pages/u/[username].js
fix: showed user's published blog in profile page 
Fixes #511 
> fix: showed user's published blog in profile page

- pages/blog.js
- pages/index.js
displayed latest published blogs on home and blog page
Fixes #489 
> fix: displayed latest published blogs on blog page and home page

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- config/config.js
- pages/admin/create-event.js
- services/EventService.js
added banner image and profile picture in event page
Fixes #500
> fix: added banner image and profile picture in event page

- pages/signup.js
fixed user is taken to forgot password page when user to try to sign up after visiting forgot password page
Fixes #508 
> fix: issue508 forgot your password page displayed when a user was created

- pages/whats-new.js
- services/PostService.js
showed tags with post in whatsnew page
showed tags with post in whatsnew page
Fixes #366 
> fix: showed tags with post in whatsnew page #366

- component/admin/AdminNavbar.jsx
- pages/admin/create-event.js
- pages/admin/index.js
- services/PostService.js
completed api intergration in admin page
Fixes #513
> fix: admin api intergration #513

- component/myblogs/MyBlogs.jsx
displayed the creation dates of blogs written by the user
Fixes #502 
> fix: issue502 display dates on which blog was created

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- component/myblogs/WriteNav.jsx
- pages/admin/create-event.js
- pages/settings.js
- services/EventService.js
- services/PostService.js
- services/SharedService.js
fixed create-event page API integration
Fixes #523 
> fix: create-event page api integration

- component/profile/BlogList.jsx
- pages/u/[username].js
- services/PostService.js
fixed published posts listing issue
Fixes #532
> fix: published posts in profile #532

- component/layout/Profile/Profile.js
- component/profile/ProfileDetails.jsx
- pages/settings.js
fixed avatar issue
Fixes #525 
> fix: profile avatar not displaying  #525

- component/myblogs/WriteNav.jsx
fixed post save slug error
Fixes #528
> fix: slug error in post save #528

- component/layout/SiteFooter/SiteFooter.jsx
- pages/tag/[tagName].js
fixed error and replaced blog into Blogs
Fixes #439 
> fix: tagname 500 error fixed #439

- pages/login.js
- pages/signup.js
Removed charecter limit for signup and login page
Fixes #531
> fix: remove charecter limit #531

- courses/javascript/objects.md
- courses/meta.js
Objects chapter added to curriculum
Added Objects chapter in curriculum
Fixes #346 
> feat: add new content objects

- component/layout/BlogPost/BlogPost.jsx
- pages/p/[postId].js
date fetching issue solved
Fixes #421 
> fix: solved date fetching issue in preview page #421

- component/layout/BlogPost/BlogPost.module.scss
- component/profile/BlogList.jsx
issue fixed in blog view and page index
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix: response issue in blog view and page index issue

- component/admin/AdminBlogsList.jsx
- component/layout/BlogListing/ListingItem.jsx
- component/layout/SiteHeader/SiteHeader.jsx
- component/profile/BlogList.jsx
- component/profile/ProfileDetails.jsx
- config/config.js
- pages/[blogPost].js
- pages/p/[postId].js
- pages/posts/index.js
- pages/settings.js
- pages/u/[username].js
- services/PostService.js
- services/TagService.js
issue fixed in profile page and blog page
Fixes #561
> fix: blog count and othor fixes #561 #556 #555

- component/admin/AdminEventList.jsx
ui updates
UI update
Fixes #547 
> fix: UI update on admin event page

- component/myblogs/Navbar.jsx
added success toast when user created a new post
> fix: added toast when user create a new post

- pages/settings.js
fixed ui issue in settings page
Fixes #560 
> 560/fix settings UI fix

- services/AuthService.js
bug fixed in update password page
Fixes #597
> fix: backend error fixed #597

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- pages/admin/events/create-event.js
added validation to create event page
Fixes #571 
> fix: added validation to create event page

- pages/login.js
fixed redirecting to forgot password page after logging in
Fixes #508 
> fix:  fixed redirecting to forgot password page after logging in

- component/admin/EventInfo.jsx
- pages/admin/events/create-event.js
fixed clicking cancel button clear the event form
Fixes #570 
> 570 cancel button not clearing the contents in the create event page

- component/myblogs/WriteNav.jsx
- pages/admin/blogs/index.js
fixed blog listing and pagination issue
Fixes #585
> fix: pagination and blog listing #585

- pages/admin/events/create-event.js
- services/EventService.js
added loader in create event button
Fixes #572 
> fix: fixed issue572 added loader in create event button

- pages/admin/events/create-event.js
redirecting to events page when cancel button is clicked in create event page
Fixes #570 
> fix: redirecting to events page when cancel button is clicked in create event page

- courses/javascript/function.md
- courses/javascript/prototypes.md
JavaScript content changed in chapter 10 and 11
Fixes #319 
Local host
> fix: content change in JavaScript 319

- component/layout/EventDetails/BookEvent.jsx
- component/layout/EventDetails/EventSpotlight.jsx
- component/layout/EventDetails/ShareEvent.jsx
- component/layout/EventDetails/ShareEvent.module.scss
- component/layout/SiteFooter/SiteFooter.jsx
- package.json
- pages/events/[event_id].js
- pages/signup.js
- services/SubscribeService.js
- yarn.lock
Added subscription option in signup and home page
Isseue #309
> Fix: Subscription 

- pages/events/[event_id].js
added event share feature 
issues  #608
@jasirtp
> Feat: Event share

- component/admin/AdminNavbar.jsx
- pages/admin/events/create-event.js
- pages/admin/events/index.js
- services/EventService.js
some minor bug fixes in event and admin blogs section
> fix: some minor bug fixes in event and admin blogs section

- component/profile/ProfileDetails.jsx
increased area of click of hovering tool on edit icon
Fixes #628 
> fix: increased area of click of hovering tool on edit icon

- component/layout/Profile/Profile.js
- component/layout/SiteHeader/SiteHeader.jsx
- pages/settings.js
name changed in popup when user updates the profiles fixed.
Fixes #607 
> fix: name changed in popup when user updates the profile

- component/layout/CourseSpotlight/CourseSpotlight.jsx
start button on UI mastery navigating to UI mastery introduction
Fixes #625 
> fix: start button on UI mastery navigating to UI mastery introduction

- pages/settings.js
Updated user upload image .
Issue #631
> fix: user-image

- component/layout/Profile/Profile.js
- pages/settings.js
removed unnecessary console logs
Fixes #641 
> 641 removing unnecessary console logs

- component/admin/OrganizerInfo.jsx
- pages/admin/events/create-event.js
- services/EventService.js
event edit page displays content on first load
Fixes #651 
> fix: event edit page displays content on first load

- component/admin/EventInfo.jsx
- services/EventService.js
minor bug fixes in update event page
> fix: minor bug fixes in event update

- component/layout/EventLayouts/EventFeatured.jsx
- component/layout/EventLayouts/EventItems.jsx
fixed event listing issues
Fixes #655 
Fixes #660 
> fix: events data listing issue fixed #655

- pages/events/[event_id].js
fixed dummy url changed into registration url
Fixes #664 
> fix: event share link changed #664

- component/layout/EventDetails/BookEvent.jsx
added title of event in add to calendar
Fixes #663 
> fix: added title of event in add to calendar

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- pages/admin/events/create-event.js
- tailwind.config.js
fixed change photo not working and while Editing the Events in the Event edit page, the already uploaded image not getting displayed
Fixes #643 #645 
> 643 fix change photo not working

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- pages/admin/events/create-event.js
- tailwind.config.js
Reverts Planet-NULLCAST/curriculum#669
> Revert "643 fix change photo not working"

- pages/index.js
fixed edit event page
Fixes #643 
> fix: minor bug fix on home page and event edit page

- component/admin/AdminEventList.jsx
- component/layout/EventDetails/BookEvent.jsx
- component/layout/EventDetails/ShareEvent.jsx
- component/layout/EventLayouts/EventFeatured.jsx
- pages/admin/events/create-event.js
- pages/events/[event_id].js
fixed event edit & location update  issue
Fixes #677
> fix: event location update error fixed  #677

- component/admin/EventInfo.jsx
- component/admin/OrganizerInfo.jsx
- pages/admin/events/create-event.js
added validation for organizer Image and Banner Image
Fixes #571 
> fix: added validation for organizer and banner image

- component/layout/BlogPost/BlogPost.jsx
- pages/p/[postId].js
fixed date toast error and blogs count
Fixes #689
> fix: issues fixed #689

- component/layout/BlogListing/Listing.jsx
- pages/blog.js
- services/PostService.js
fixed load more button showing same blogs
Fixes #691 
> fix: fixed loadmore button showing same blogs

- component/layout/CourseSpotlight/CourseSpotlight.jsx
- courses/meta.js
- pages/curriculum/[courseName]/[chapterName].js
- pages/curriculum/[courseName]/index.js
- pages/index.js
- services/CurriculamService.js
fixed cookies not defined
Fixes #621 
> fix: cookies not defined error

- component/layout/BlogPost/BlogPost.jsx
> fix: issues fixed #693

- config/config.js
- pages/signup.js
- pages/u/[username].js
- pages/verify-user.js
- services/AuthService.js
added email verification api
Fixes #695 
> fix: verify email api connected #695

- component/myblogs/WriteNav.jsx
- pages/settings.js
- services/SkillService.js
- services/TagService.js
fixed post tag user skill multiple  deletion and tag listing in alphabetical order
Fixes #592 
> fix: delete all tags and user skills also fixed tag sort #592

- pages/posts/index.js
sorting order issue during the deletion of the blogs fixed
Fixes #616 
> fix: sorting order issue in the list of the blogs #616

- component/layout/HomeSpotlight/HomeSpotlight.jsx
- component/layout/HomeSpotlight/HomeSpotlight.module.scss
added Christmas spotlight
Fixes #712 
> feat: christma season spotlight added #712

- component/profile/ProfileDetails.jsx
- pages/admin/events/index.js
added scroll when bio exceeds and event undefined error in admin events page
Fixes #580 
> fix: added scroll when bio exceeds and event undefined error in admin events page

- component/myblogs/MyBlogs.jsx
- component/myblogs/WriteNav.jsx
Fix the pagination of blog listing page when user cam back to the page after editing the blog
> #486 fix: Blog Pagintaion

- component/layout/EventLayouts/EventListing.jsx
- pages/events/index.js
fixed load more button in user events page
Fixes #718 
> fix: fixed load more button in user events page

- component/layout/EventLayouts/EventFeatured.jsx
- component/layout/EventLayouts/EventItems.jsx
- config/config.js
- pages/e/[event_slug].js
- services/EventService.js
event view by slug api connected and change /events into /e
Fixes #724
> fix: get event by slug api connected #724

- component/layout/EventDetails/ShareEvent.module.scss
- pages/events/[event_id].js
disable scroll on share event
Disabled scroll on share event
and close area enlarged
> #722 Share event scroll

- pages/signup.js
full name validation for sign up page
Fixes #492 
> fix: full name validation for sign up page

- component/pagination/pagination.jsx
- pages/admin/blogs/index.js
- services/PostService.js
fixed multiple filter working in admin blog list
Fixes #729 
> fix: multiple filter not working in admin blog list

- pages/curriculum/[courseName]/[chapterName].js
- services/CurriculamService.js
fixed ui  mastery error
Fixes #735 
> fix: ui mastery error fixes #735

- courses/ui-mastery/html.md
- courses/ui-mastery/introduction.md
UI mastery chapter 1 and 2 fixes
Fixes #622 
- [] I have made corresponding changes to the documentation
> fix: ui mastery fixes

- styles/Settings.module.scss
replaced cursor pointer to normal arrow(svg)
Fixes #541 
> fix: replace cursor pointer to normal arrow

- pages/admin/blogs/index.js
all post tag fix in multiple filter admin blogs
Fixes #729 
> fix: all post tag in multiple filter admin blog

- pages/admin/events/create-event.js
added title for create event page
Fixes #743 
> fix: added title for create event page

- component/layout/SectionEvents/SectionEvents.jsx
- next.config.js
- pages/admin/events/create-event.js
added solution code in next.config
Fixes #741 
> fix: added solution in next.config #741

- component/layout/WhatsNew/WhatsNewPosts.jsx
- pages/whats-new.js
Added published status in whatsnew page and commented the code block
> fix: added published status in whatsnew

- component/myblogs/WriteNav.jsx
- pages/posts/write.js
fixed and added title and content update with post settings save
Fixes #529 
> fix: added title content updation with settings save button #529

- component/profile/BlogList.jsx
- component/profile/FollowersList.jsx
Change the style of blog listing in profile page
add view all link
commented the followers list
> Fix: Blog List in Profile page

- .gitignore
- component/layout/CourseList/CourseList.jsx
order change removed learn html and learn css 
Fixes #748 
> fix: order change curriculam course #748

- component/admin/AdminEventList.jsx
added routing via slug in admin event list 
Fixes #750
> fix: added routing via slug in admin event list

- component/admin/AdminBlogsList.jsx
- component/admin/AdminNavbar.jsx
fixed admin status and added drafted status filter
Fixes #633 
> fix: blog status in admin page and drafted fillter added #633

- component/layout/WhatsNew/WhatsNewPosts.jsx
Fixed the email subscription in the whatsnew page
removed the dummy data in whatsnew page
> Fix: Email Subscription in whatsnew

- pages/events/index.js
fixed event termination and listing issues
Fixes #761 
> fix: event termination and listing issues fixed #761

- component/layout/BlogListing/ListingItem.jsx
removed featured blog from bloglist
Fixes #779 
> fix: removed featured blog from bloglist

- pages/e/[event_slug].js
changed share event url
Fixes #773 
> fix: share event url changed #773

- component/profile/ProfileDetails.jsx
- pages/u/[username].js
- services/AuthService.js
fixed logout issue
Fixes #509 
> fix: logout issue #509

- component/admin/AdminEventList.jsx
event view added in admin event list
Fixes #771 
> fix: event view added in admin event list #771

- component/layout/achievement/AchievementCategory.jsx
- component/layout/achievement/AchievementList.jsx
- pages/u/achievement.js
fixed achievement page UI and achievement filtering
Fixes #759 
> 759/fix achievement page UI changes

- component/myblogs/MyBlogs.jsx
- styles/globals.scss
Changed the filter color to white
#488
> Enhancement: Blog Filter colour

- component/admin/EventInfo.jsx
- component/layout/EventDetails/Detail.jsx
- package.json
- yarn.lock
> fix: build error #782

- component/layout/EventLayouts/EventDate.jsx
- pages/events/index.js
fixed current day's event not showing up
Fixes #784 
> fix: current day's event not showing up

- component/myblogs/WriteNav.jsx
fixed upload banner_image
Fixes #790 
> fix: image upload error #790

- lib/notify.js
Disappear toast when user start writing on the blog
Fixes #416
> Fix: disapperaing toast

- component/layout/SectionEvents/SectionEvents.jsx
- pages/index.js
route section event to event detail page
Fixes #788 
> fix: routed section event to event detail page

- component/admin/AdminEventData.jsx
- component/admin/AdminEventList.jsx
- component/admin/AdminEventSidebar.jsx
- pages/admin/events/[event_id]/attendees.js
- pages/admin/events/[event_id]/index.js
- pages/u/[username].js
added event attendees page
Fixes #774 
> feat: added event attendees page

- component/admin/AdminEventList.jsx
- pages/admin/events/create-event.js
added preview button when event is updated and view the event in new tab when viewing from admin page
Fixes #786 
> feat: added preview button and view the event in new tab when viewing from admin page

- component/layout/EventLayouts/EventDate.jsx
- pages/admin/events/create-event.js
redirected user to event page when time is over and added validation for updating event
Fixes #798 
> fix: redirected user to event page when time is over and added validation for updating event

- pages/signup.js
Changed checkbox size and cursor
#795
> Fix: Checkbox in Signup Page

- pages/login.js
added validation in login page email field
Fixes #313 
> fix: added validation

- component/layout/SectionVideos/SectionVideos.jsx
- component/layout/SectionVideos/SectionVideos.module.scss
fixed superbased videos
Fixes #491 
> fix: superbase #491

- component/myblogs/WriteNav.jsx
- pages/settings.js
fixed down indicater ui issue in blog and profile settings page
Fixes #591 
> fix: blog tags view   #809

- component/myblogs/Navbar.jsx
- pages/posts/index.js
added search in write
Fixes #506 
> fix: usr blog search fixed  #506

- component/layout/SectionVideos/SectionVideos.jsx
> fix: superbase video fixed  #131

- component/layout/EventDetails/BookEvent.jsx
- component/layout/EventDetails/BookEvent.module.scss
- component/layout/EventLayouts/EventDate.jsx
- component/layout/EventLayouts/EventItems.jsx
- pages/events/index.js
added ended tag for completed events on event list and and event ended for completed events on event details page
Fixes #817 
> added ended tag for completed events on event list and and event ended for completed events on event details page

- component/layout/SectionVideos/SectionVideos.jsx
fixed home video controller issue
Fixes #491 
> fix: home superbase video controll issue #491

- .dockerignore
- Dockerfile
Dockerize the application
- Add Dockerfile
- Add .dockerignore
Fixes #835 
Tested Dockerfile by building and running a docker container. Verified the front-end.
Instructions to reproduce
- Clone the forked repository and switch to branch 835-feat/Docker
- In a shell with docker installed, run command `docker build -t <tag-name> .` to build the container
- Then to run the container, run `docker run -it --rm -p3000:3000 -t <tag-name>`
OS : Ubuntu 21.04
Docker Version: Docker version 20.10.7, build 20.10.7-0ubuntu5.1
> feat: Dockerize Application

- component/layout/CourseSpotlight/CourseSpotlight.jsx
fixed course not found issue when get started for free button is clicked on the curriculum page
Fixes #829 
> fix: fixed course not found issue

- pages/events/index.js
- services/EventService.js
- services/PostService.js
changed put functions to patch
Fixes #824 
> fix: changed put function to patch

- component/layout/HomeSpotlight/HomeSpotlight.jsx
- component/layout/HomeSpotlight/HomeSpotlight.module.scss
- styles/globals.scss
removed Christmas theme from home spotlight and and cursor
Fixes #826
> fix: removed Christmas theme

- component/layout/CourseSpotlight/CourseSpotlight.jsx
fixed course not found for merging into development
Fixes #826 
> fix: fixed course not found issue (for development)

- component/layout/HomeSpotlight/HomeSpotlight.jsx
- component/layout/HomeSpotlight/HomeSpotlight.module.scss
- styles/globals.scss
removing Christmas theme for merging into development
Fixes #826 
> fix: removed christmas theme (for development branch)

- pages/login.js
- pages/signup.js
fixed password eye issue in login and sign up page
Fixes #834 
> fix: password eye issue

- component/leadership/Tabs.jsx
- component/leadership/tabs.module.scss
- component/pagination/paginationLeaderBoard.jsx
- config/config.js
- pages/admin/blogs/index.js
- pages/leaderboard.js
- services/LeaderBoardService.js
leaderboard ui and api integration
Fixes #840 
> feat: leaderboard ui api #840

- component/layout/SectionEvents/SectionEvents.jsx
fixed home event ui issue
Fixes #831 
> fix: ui issue home event #831
